server:
  port: 8761


#Telling the eureka client to NOT register by itself.
# Read for more details : https://stackoverflow.com/questions/63656516/what-is-the-use-of-wait-time-in-ms-when-sync-empty-in-spring-eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 #wait time for subsequent sync.
  instance:
    hostname: localhost
