server:
  port: 9091
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app_apis
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true #This will basically show you hibernate query.